server {
    server_name xn--80aa4agjld3h.xn--p1ai www.xn--80aa4agjld3h.xn--p1ai;

    client_max_body_size 20M;

    location /api/ {
    proxy_pass http://127.0.0.1:4000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout 90s;
}

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 90s;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/xn--80aa4agjld3h.xn--p1ai/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/xn--80aa4agjld3h.xn--p1ai/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = www.xn--80aa4agjld3h.xn--p1ai) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = xn--80aa4agjld3h.xn--p1ai) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name xn--80aa4agjld3h.xn--p1ai www.xn--80aa4agjld3h.xn--p1ai;
    return 404; # managed by Certbot




}
